services:

  omekas:
    build: .
    depends_on:
      - omekas_db
    image:  giocomai/omeka-s-docker:latest
    container_name: omekas
    ports:
      - "8000:80"
    restart: unless-stopped
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: O1-rs-NAS
      MYSQL_DATABASE: omekas
      MYSQL_HOST: omekas_db
      APPLICATION_ENV: development                                                     
      PHP_MEMORY_LIMIT: 512M
      PHP_UPLOAD_MAX_FILESIZE: 64M
      PHP_POST_MAX_SIZE: 64M
      PHP_MAX_EXECUTION_TIME: 300
      OMEKA_ADMIN_EMAIL: nicholas.cornia@orpheusinstituut.be
      OMEKA_ADMIN_NAME: "Site Administrator"
      OMEKA_ADMIN_PASSWORD: O1-rs-NAS
      OMEKA_SITE_TITLE: "Orpheus Instituut DAM"
    volumes:
      - type: bind
        source: ./files
        target: /var/www/html/volume/files
      - type: bind
        source: ./config
        target: /var/www/html/config
      - type: bind
        source: ./modules
        target: /var/www/html/volume/modules
      - type: bind
        source: ./themes
        target: /var/www/html/volume/themes
  omekas_db:
    image: mysql:latest
    container_name: omekas_db
    restart: unless-stopped
    volumes:
      - omekas_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: O1-rs-NAS 
      MYSQL_DATABASE: omekas_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: O1-rs-NAS

volumes:
  omekas_db_data:
 